### ISSUE TITLE
求分享主题CSS文件。

### ISSUE THREAD

**Issue by frankelinli** [yuannancheng/fictional-university#1]
请问可以分享下这个项目的主题style.css吗？谢谢。

**Comment by yuannancheng** [comment]
你好，这个主题开发使用到了前端构建工具，主题样式相关的源码会在发布前构建成压缩版本，然后在 [functions.php](https://github.com/yuannancheng/fictional-university/blob/5a234d098439657e4c9f3d1367dd471e54310e7a/functions.php#L50) 文件中加载，主题根目录下的 `style.css` 仅作为主题的相关信息声明文件，不作为实际的样式表，所以没有样式相关的内容。

可以看看下面的帮助信息，或许对你有帮助：
- 本仓库参考的课程: <https://www.bilibili.com/video/BV1b3411G7wL/>
- 主题样式相关的源码入口文件是 <https://github.com/yuannancheng/fictional-university/blob/main/css/style.scss>

**Comment by frankelinli** [comment]
感谢答疑解惑。推荐的视频课程非常非常优秀。CSS源码已看到，在逐步学习参考。感谢大佬。

**Comment by yuannancheng** [comment]
不客气，加油
